### ISSUE TITLE
Poor User Experience When Words Repeat

### ISSUE THREAD

**Issue by fullstackman** [Emily1799/TypeFun#1]
Just found this through the HackBU submissions. Reminds me a lot of this game: http://candies.aniwey.net/ 
After trying it out, I noticed that I would get stuck waiting for some kind of visual cue whenever I typed a one letter word (like "s") and the word didn't change. I realized that it's because I typed the right letter but the new letter is a repeat.
I'll modify this code later and add a CSS animation that lets players know that they typed the word correctly.

**Comment by Emily1799** [comment]
Cool! I don't' know much css, so feel free to do it and submit a pull
request on Github. I need to add a license, and I'I'm thinking copy left...

Thanks for the feedback

**Comment by Emily1799** [comment]
OK, so I actually fixed this (as a temporarily fix, the updateWord function now checks if index is the same as the previous index). But if you still want to do that, just remove my prevword stuff. Either way, thanks for bringing it up in the first place!
